GET http://localhost:5000/siswa
###
GET http://localhost:5000/siswa/1000
###
POST http://localhost:5000/siswa
Content-Type: application/json

{
    "nama": "Arzaki",
    "kelas": "XI",
    "jurusan": "RPL",
    "alamat": "Kr",
    "gender": "L",
    "nohp": "089669572100"
}
###
PATCH  http://localhost:5000/siswa/1000
Content-Type: application/json

{
    "nis": "999",
    "nama": "Thoriq Hanif",
    "kelas": "XI",
    "jurusan": "RPL",
    "gender": "L",
    "alamat": "Surakarta",
    "nohp": "081"
}
###
DELETE  http://localhost:5000/siswa/1001

# KELAS
###
GET http://localhost:5000/kelas
###
GET http://localhost:5000/kelas/1
###
POST http://localhost:5000/kelas
Content-Type: application/json

{
    "nama": "XI",
    "jumlah": "36"
}
###
PATCH  http://localhost:5000/kelas/1000
Content-Type: application/json

{
    "kode_kelas": "1",
    "nama": "XI",
    "jumlah": "36"

}
###
DELETE  http://localhost:5000/kelas/1

# USER

###
GET http://localhost:5000/user
###
GET http://localhost:5000/user/b020e3d5-4721-4b60-9598-a7fa3012bf18
###
POST http://localhost:5000/user
Content-Type: application/json

{
    "nama": "guru",
    "email": "guru@gmail.com",
    "password": "guru",
    "confPassword": "guru",
    "role": "guru"
}
###
PATCH http://localhost:5000/user/3ad9fa03-df56-4a96-9c2f-68b79f26a887
Content-Type: application/json

{
    "nama": "admin",
    "email": "admin@gmail.com",
    "password": "admin",
    "confPassword": "admin",
    "role": "admin"
}
###
DELETE http://localhost:5000/user/24737397-e8ec-4987-afc2-69c2945da76f
# LOGIN
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"admin"
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"user@gmail.com",
    "password":"123"
}

###
GET http://localhost:5000/me

###
DELETE http://localhost:5000/logout
















